name: test workflow

on:
  workflow_dispatch:
    inputs:
      site:
        description: Site
        required: true
        type: environment
        default: int
  push:
    branches:
      - main
    tags:
      - release/int/*

permissions:
  id-token: write
  contents: read

jobs:
  init-job:
    environment: |-
      ${{ contains(github.ref_name,'release/int/') && 'int' || 'dev' }}
    runs-on: ubuntu-latest
    name: "Init Job"
    steps:
      - run: | 
          echo "Init Job on ${{ vars.ENVIRONMENT }}"
          echo "Ref Name: ${{ github.ref_name }}"
